stages:
  - AdventOfCode

.ruby: &ruby_template
  image: ruby:2.7
  script:
    - file=$(echo $CI_JOB_NAME | grep -o "[0-9][0-9]")
    - ruby code/$file.rb
  stage: AdventOfCode

day_07:
  <<: *ruby_template
